//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KITAPLIK.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KıtapEntities3 : DbContext
    {
        public KıtapEntities3()
            : base("name=KıtapEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorıler> Kategorıler { get; set; }
        public virtual DbSet<KıtapDetay> KıtapDetay { get; set; }
        public virtual DbSet<Kıtaplar> Kıtaplar { get; set; }
        public virtual DbSet<Kutuphanem> Kutuphanem { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<yazarlar> yazarlar { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
