//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KITAPLIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutuphanem
    {
        public int kıtapıd { get; set; }
        public int uyeıd { get; set; }
        public Nullable<bool> okuyacaklarım { get; set; }
        public Nullable<bool> okuduklarım { get; set; }
        public Nullable<int> yorumlarııd { get; set; }
    
        public virtual Kıtaplar Kıtaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
        public virtual Yorum Yorum { get; set; }
    }
}
