//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KITAPLIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KıtapDetay
    {
        public int kıtapıd { get; set; }
        public string kıtapcevırmenı { get; set; }
        public string kıtapbasım { get; set; }
        public Nullable<short> kıtapsayfa { get; set; }
        public string kıtapdılı { get; set; }
        public string kıtapyayınevı { get; set; }
    
        public virtual Kıtaplar Kıtaplar { get; set; }
    }
}
