//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KITAPLIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorum()
        {
            this.Kutuphanem = new HashSet<Kutuphanem>();
        }
    
        public int Yorumıd { get; set; }
        public string yorum1 { get; set; }
        public int uyeıd { get; set; }
        public int kıtapıd { get; set; }
    
        public virtual Kıtaplar Kıtaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kutuphanem> Kutuphanem { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
